### ISSUE TITLE
GoDBLedger 2021 / 2022 roadmap

### ISSUE THREAD

**Issue by mingsterism** [darcys22/godbledger#167]
Can we have feature list roadmap for GoDBLedger for the next 1-2 years? 
If we could have this would be great to understand the future direction of the system and where it's headed. The current list on github just shows a few current immediate features. 

some of my ideas are
1)  transaction classification. Automated? 
2) add transaction approvals / reject
3) analytics on transactions. 
4) linking transactions to balance sheet (from the list of transaction, one is able to determine the current liabilities / assets of the business)
5) automated bank reconciliation? Integrating into bank feeds?

**Comment by darcys22** [comment]
Thanks for raising this. I have created #169 as a result which is great because we can direct people to it in the future and discuss there what plans and ideas are.

In response to your ideas most are already planned.

1. Yes, but low priority compared to getting a user friendly system build
2. Half concieved idea for this already exists #28 and code exists for different users would simply be a matter of coding in some middleware for logic on approve/reject. 
3. Probably deferring this onto external Business Analytics software packages, one of the advantages of having our open database is that Tableau/Metabase etc can analyse it very easily and is more suited to how Data Analysts work in the real world. Future possibility of building something simple into GoDBLedgers dashboard
4. Not sure I understand this one, transactions drive the balance sheet numbers so they are inherently linked already.
5. Definitely, short term high priority for this

**Comment by darcys22** [comment]
I'm going to close this issue to avoid the conflicting name and defer people to #169. Can discuss your features further there if you wish?
